version: "3.8"
services:
  api-service:
    build:
      context: ./api_service
      args:
        PORT: ${API_PORT:-8000}
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    environment:
      - PORT=${API_PORT:-8000}
    restart: unless-stopped
    depends_on:
      - db
      - minio
    volumes:
      - ./api_service:/app

  internal-service:
    build:
      context: ./api_service
      args:
        PORT: ${API_PORT:-8001}
    ports:
      - "${API_PORT:-8001}:${API_PORT:-8001}"
    environment:
      - PORT=${API_PORT:-8001}
      - INTERNAL_MEDIA_SERVICE = 1
    restart: unless-stopped
    depends_on:
      - db
      - minio
    volumes:
      - ./api_service:/app

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER:-minioadmin}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
